spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/uyoaix/springcloud-config-repo
server:
  port: 9060
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/